### PR TITLE
Fiss site data tidy and backup files

### PR DESCRIPTION
**Pull request by Mateo9569**
NOTE: there is an amalgamated fiss site form that is now in the mergin project (file name is `form_fiss_site_20231027.gpkg`). Make sure to sync first. Let me know if it doesn't show up for you. I backed up the original fiss site files, but made all the changes in Q to the amalgamated version.

### CODE REVIEW

**Review by NewGraphEnvironment — APPROVED** [review]

**Review by NewGraphEnvironment — APPROVED** [review]
looks good 

is there a call missing to `row_empty_remove = T` or some other small thing when you ran the backup for the hab_con input?  Something is off with the backups as none have the correct column names.... will test once i merge

**Comment by NewGraphEnvironment** [comment]
yup.  that was it.  lookin great now - row_empty_remove allows those top excel sheet rows to be discarded (because they are just a few columns wide) for the real column header names

`fpr::fpr_import_hab_con(row_empty_remove = T)`

image

**Comment by NewGraphEnvironment** [comment]
Data files are looking tight. Nice work. We are on our way!

**Comment by Mateo9569** [comment]
Thanks. Ya sorry I ran `fpr::fpr_import_hab_con` in the console right before I pushed so the backup files would all be there too and forgot to add the `row_empty_remove = T` call

**Pull request merged**
